server:
  port: 8082
spring:
  application:
    name: teamfight-tactics-api
  web:
    resources:
      add-mappings: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/TeamfightTactics
    web:
      pageable:
        default-page-size: 30
teamfight-tactics:
  api-key: ${API_KEY}