server:
  port: 8080
spring:
  application:
    name: teamfight-tactics-api
  web:
    resources:
      add-mappings: false
  data:
    mongodb:
      uri: ${MONGO_DATABASE_URL}TeamfightTactics
    web:
      pageable:
        default-page-size: 30
teamfight-tactics:
  api-key: ${API_KEY}